publishers:
  - id: primary-sqs
    type: sqs
    enabled: true
    sqs:
      uri: "https://sqs.ap-south-1.amazonaws.com/1234567890/link-events"
      region: "ap-south-1"

  - id: webhook
    type: http
    enabled: true
    http:
      url: "https://example.com/hooks/link-events"
      method: POST
      timeout_seconds: 5
      headers:
        X-Auth-Token: "secret-token"


# Note: Do NOT commit actual credentials into this file. Keep secrets in env or secret manager.
